# Generated by Django 5.2.1 on 2025-05-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_wasteinput_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wasteinput',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
