# Generated by Django 5.2.1 on 2025-06-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_adminlog_message_alter_adminlog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('DELETE', 'Delete'), ('UPDATE', 'Update'), ('INFO', 'Info')], max_length=25),
        ),
    ]
